defaults:
  - /sim/sloshing@sloshing: no_sloshing
  - /sim/sc@sc: sc_default
  - _self_

sim_time: 100.0   # [sec]
sim_dt: 0.01      # [sec] Dynamics integration step
ctrl_dt: 0.1        # [sec] Control update step
log_dt: 0.1       # [sec] Data logging step
warmup_time: 10.0 # [sec] Wait for history buffer to fill

target_attitude: [1.0, 0.0, 0.0, 0.0] # Quaternion [q0, q1, q2, q3]

show_plots: true
use_vizard: false

env:
  include_sun: true   # For gravity effector
  enable_drag: true
  enable_srp: true

sensors:
  rng_seed: 42
  nav_noise:
    pos: 0.0      # [m]
    vel: 0.0      # [m/s]
    att: 0.0      # [rad] (sigma)
    rate: 0.0     # [rad/s]
