_target_: src.models.model_lti.LTIModel
_recursive_: False

defaults:
  - context: kimi
  - lifting: resnet
  - matrix: linear
  - _self_

state_dim: ${data.state_dim}
control_dim: ${data.control_dim}
latent_dim: 64

eigval_max: 1.05