_target_: src.models.components.block_kimi.KimiBlock

hidden_size: 64
num_layers: 4
num_heads: 4

kda:
  norm_eps: 1e-6
  allow_neg_eigval: False
  expand_v: 1.0
  use_short_conv: True
  conv_size: 4

mla:
  kv_lora_rank: 16
  window_size: null
  qk_norm: True
  q_lora_rank: null