_recursive_: False

defaults:
  - optimizer: adamw
  - scheduler: cosine
  - callbacks: early_stopping
  - _self_

batch_size: 64
num_workers: 4
epochs: 100
grad_clip_norm: 1.0
pred_steps: 100
val_steps: ${test_steps}
test_steps: 100

seq_strategy:
  warmup_epochs: 10
  warmup_steps: 5
  min_steps: 10
  max_steps: 100