_recursive_: False

defaults:
  - data: attitude
  - model: model_lti
  - loss: loss_default
  - train: train_default
  - _self_

wandb:
  project: "2025-koopman"
  entity: null
  group: "lti"
  mode: "online"