_recursive_: False

defaults:
  - data: attitude
  - model: model_lpv
  - loss: loss_default
  - train: train_default
  - _self_

wandb:
  project: "2025-koopman"
  entity: null
  group: "lpv"
  mode: "online"

hydra:
  run:
    dir: outputs/learning/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/learning/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}