_target_: sim.controller.bsk_koopman_mpc.BskKoopmanMPC

checkpoint_dir: "2025-12-24/14-26-34"
device: "cuda"

mpc_params:
  horizon: 20
  Q_diag: [10.0, 10.0, 10.0, 10.0, 1, 1, 1]
  R_diag: [0.5, 0.5, 0.5]
  F_diag: [100.0, 100.0, 100.0, 100.0, 10, 10, 10]
  Q_rest: 0.1
  F_rest: 1
