_target_: sim.controller.koopman_mpc.BskKoopmanMPC

checkpoint_dir: "2025-12-24/14-26-34"
device: "cuda"

mpc_params:
  horizon: 20
  Q_diag: [10.0]
  R_diag: [0.01, 0.01, 0.01]
  F_diag: [200.0]
  rest_ratio: 1.0
  u_min: -1.0
  u_max: 1.0
  
