_target_: src.models.components.block_veronese_2.VeroneseLifting2
quat_indices: ${data.quat_indices}

# Neural Network Backbone Configuration
# (Used for non-Veronese dimensions)
backbone:
  _target_: src.models.components.block_resnet.ResNetBlock
  hidden_size: 128
  num_layers: 2
  use_norm: true
  activation: 
    _target_: torch.nn.SiLU

